LaughLax/icarus5

README.md, modules/botAdmin.js
*Curmudgeonly grumbles at Gai*
=> JSdoc things please

config/config-example.json, registry/rank.json, utils/utils.js
* No changes to bot config file required.
* No changes to any Interaction fingerprints.
* No changes requiring updates to documentation.
* No snowflakes involved in changes.
=> Misc fixes

package-lock.json, package.json
Properly set the `augurbot` source as the git repo, include some dependencies I know Ryn's PR will require.
=> Additional dependencies

modules/bookmark.js, registry/bookmark.json, utils/utils.js
Basic bookmark message context command, so we can get a low-level I5 running alongside I4.
=> Bookmark initial commit

README.md, modules/bank.js, package.json
Avoid error message from `/bank game` commands by calling `deferReply()` immediately and then editing the reply.
Send multiple embeds per message in `/bank game list` to reduce messages sent by Icarus.
Also a couple little updates to package.json and readme.md
=> A couple improvements in bank.js

config/config-example.json
remove the applicationId, no longer needed.
=> removing unnecessary field

utils/utils.js
This reverts commit b28f9cb5fb07cedeccc0bcea7ad74443e311bf13, reversing
changes made to 750cc58db0b077d5a463e67014709e5f1681dfca.
=> Revert PR 20 for further review

modules/bank.js
Intended to handle the error message at https://discord.com/channels/111232928784072704/806198463125127188/887175967146115153
=> If no reason provided in `/bank give`, don't error out

modules/bank.js
- Are any changes to config.json necessary? If so, are they reflected in config-example.json?
- - No changes to config needed.
- Are all referenced snowflakes contained in the config/snowflake.json file, rather than in the code directly?
- - No snowflakes are directly included in this code.
- Are any changes to Interaction fingerprints needed? If so, are they reflected in the appropriate file in /registry?
- - No changes to Interaction fingerprints are needed.
- Have I used JSdoc style comments (at least) to properly document all of my functions?
- - No new functions were created.
- Are there any new dependencies that need to be installed? If so, are they reflected in package.json?
- - No new dependencies are needed.
=> Catch and handle error in `/bank game list` if DM to user fails

utils/utils.js
Okay, trying again. This is a "duplicate" of [PR 20](https://github.com/Gaiwecoor/icarus5/pull/20), resubmitted after a reversion so that better review can happen. **Please, nobody approve this PR until these changes have been discussed with and approved by Gaiwecoor.**
This PR aims to make the error messages for interactions more useful by including more information about the interaction. It also includes a bugfix replacing a `message.deferred` check with `message.deferred || message.replied`.
* Are any changes to config.json necessary? **No**
* Are all referenced snowflakes contained in the config/snowflake.json file, rather than in the code directly? **No snowflakes referenced**
* Are any changes to Interaction fingerprints needed? **No**
* Have I used JSdoc style comments (at least) …
=> Improve interaction error message

.eslintrc.json, models/User.model.js, modules/01-filter.js, modules/bookmark.js, modules/botAdmin.js, utils/snipcart.js, utils/utils.js
"Unnecessary escape" warnings ignored for now. I want to make sure I understand what's going on with those before I touch them.
=> Address most linter warnings

modules/01-events.js, modules/01-filter.js, modules/01-mods.js, modules/bank.js
Some places didn't get replaced, such as a public message in a public channel, to avoid double pings. Also embed authors, obviously.
Noticed a bug with this branch: utils.js:77, Module does not exist there
=> Replace displayName with toString(), where feasible.

.eslintrc.json, package.json
1. Remove duplicate config in `package.json` that currently does nothing
2. Allow banner-style comments that have extra asterisks. For example:
```js
/********************
**  Filter Events  **
********************/
```
=> Adjust ESLint config

package-lock.json
This PR updates `package-lock.json` but does not modify `package.json`.
=> Address multiple vulnerabilities

modules/01-filter.js, modules/01-mods.js, registry/mod.json
Fixes #38 
Fixes #62
Also fixes a minor summary bug with the previous PR.
=> Add `/mod fullinfo`, and fix #38.

modules/01-mods.js, modules/botAdmin.js, utils/perms.js
=> Create and use utils/perms.js

modules/01-filter.js
=> Fix Issue 67 (bug in `warnCard()`)

modules/cake.js
=> Don't apply color roles for cake days

database/controllers/user.js
=> Fix references in db.user to other DB functions

modules/cake.js
Fix has been tested and works 👍
Fixes #68
=> Apply and remove roles at the same time

modules/bank.js
=> Change, fixes #74

modules/01-mods.js
=> Remove hierarchy check from `/mod mute` and `/mod office`

modules/01-mods.js
=> Move text to embed description

modules/rank.js
Fixes #96
Also shrinks the try/catch to per-user and de-anonymizes the function for better stack traces.
=> Bugfix rank clockwork

data/modMenuFlagOptions.json, data/modMenuOptions.json, modules/01-mods.js, modules/modMenu.js, utils/modCommon.js, utils/perms.js, utils/utils.js
Menu items added:
* Flag User
* Trust User
* Trust+ User
* Purge Channel
* Timeout User (kept disabled)
Other changes:
* Menu-ing moved into its own function
* Fewer ephemeral messages created
* Allow Management to announce messages
=> Add items to Moderation menu

modules/cake.js
=> Sort cake day fields from longest tenure to shortest

config/snowflakes-example.json, modules/eliteDangerous.js, utils/EliteApi.js
Feature to auto-post Galnet feeds in `#Galnet Feed`.
No new dependencies. One new snowflake.
=> Galnet feed initial commit

config/config-example.json, modules/01-filter.js, modules/01-mods.js
Resolves #93 and #141 
Since its a small enough change, I've also included a fix for #95
=> Prevent self-handling of flags, log slowmode=0

modules/01-filter.js
=> Replace and repost announced posts with invites
